chore: shared to all subdomains

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -43,6 +43,12 @@ jobs:
 
       - name: Build
         run: bun run build
+      - name: Test if dist directory exists
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Error: dist directory does not exist. Build failed."
+            exit 1
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
